name: KinomePred
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - charset-normalizer=3.1.0
  - contourpy=1.1.0
  - cycler=0.11.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.40.0
  - freetype=2.12.1
  - freetype-py=2.4.0
  - gettext=0.21.1
  - greenlet=2.0.2
  - icu=72.1
  - idna=3.4
  - joblib=1.2.0
  - kiwisolver=1.4.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.3
  - libgomp=13.1.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxgboost=1.7.4
  - libzlib=1.2.13
  - lightgbm=3.3.5
  - matplotlib-base=3.7.1
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.25.0
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - pandas=2.0.2
  - pcre2=10.40
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.8.0
  - pooch=1.7.0
  - pthread-stubs=0.4
  - py-xgboost=1.7.4
  - pycairo=1.24.0
  - pyparsing=3.1.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - readline=8.2
  - reportlab=4.0.0
  - requests=2.31.0
  - rlpycairo=0.2.0
  - scikit-learn=1.2.2
  - scipy=1.11.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlalchemy=2.0.17
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=2.0.3
  - wheel=0.40.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - bounded-pool-executor==0.0.3
      - click==8.1.7
      - mold2-pywrapper==0.0.4
      - more-itertools==10.1.0
      - pyaml==23.9.7
      - pystow==0.5.2
      - pyyaml==6.0.1
      - rdkit==2023.9.2
      - scikit-optimize==0.9.0
      - tqdm==4.66.1
